### ISSUE TITLE
compilation error when luarocks install 

### ISSUE THREAD

**Issue by czheo** [noahdesu/lua-rados#21]
On ubuntu 16.04, when do `luarocks install https://raw.github.com/noahdesu/lua-rados/master/rockspecs/lua-rados-0.0.1-1.rockspec`, there is a compiler error as below:
```
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```

**Comment by noahdesu** [comment]
Please try with `lua-rados-0.0.2-1.rockspec` and let me know if there are any issues with that version.

**Comment by czheo** [comment]
👍  it works perfect.
